name: Deploy to dev

on:
  push:
    branches: [ main ]

jobs:
  re_deploy_app:
    name: Re Deploy app to dev
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
      - run: |
          echo ${{ secrets.TEST_SSH_PRIVATE}} &> ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -i ~/ssh_key ubuntu@13.203.193.91
          cd /home/ubuntu/cicd-gh-actions && git pull
          npm install
          npm run build
          pm2 restart "next app"