name: Deploy to dev

on:
  push:
    branches: [main]

jobs:
  re_deploy_app:
    runs-on: ubuntu-latest
    name: Re Deploy app to dev
    steps:
      - run: |
          echo "${{ secrets.TEST_SSH_PRIVATE}}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS}}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@13.233.156.10 -t "cd /home/ubuntu/cicd-gh-actions && git pull origin main && export PATH=/home/ubuntu/.nvm/versions/node/v22.15.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install && npm run build && pm2 restart next-app"
